### ISSUE TITLE
Build breakage when installing the pydatalab library

### ISSUE THREAD

**Issue by ojarjur** [googledatalab/datalab#1160]
This is consistently repeatable and only started today without any corresponding code changes (so it was most likely caused by an upstream package changing).

An example build failure is [here](https://travis-ci.org/googledatalab/datalab/builds/196048148).

**Comment by yebrahim** [comment]
I've seen this issue before with outdated setuptools version.

**Comment by parthea** [comment]
I hit this exact error today as well but I wasn't able to find the root cause. At first I thought it was only my environment but I'm glad to hear it is repeatable.

**Comment by yebrahim** [comment]
@parthea did you hit it on travis or in your local setup?

**Comment by parthea** [comment]
@yebrahim The error appeared in my local setup. 

```
tony@tony-laptop:~/datalab-parthea/containers/datalab$ ./build.sh 
...
...
...
Processing /datalab/lib/pydatalab
Requirement not upgraded as not directly required: future==0.15.2 in /usr/local/lib/python2.7/dist-packages (from datalab==0.1.1701291609)
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 666, in _prepare_file
    check_dist_requires_python(dist)
  File "/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/utils/packaging.py", line 48, in check_dist_requires_python
    feed_parser.feed(metadata)
  File "/usr/lib/python2.7/email/feedparser.py", line 177, in feed
    self._input.push(data)
  File "/usr/lib/python2.7/email/feedparser.py", line 99, in push
    parts = data.splitlines(True)
AttributeError: 'NoneType' object has no attribute 'splitlines'
The command '/bin/sh -c ipython profile create default &&     jupyter notebook --generate-config &&     if [ -d /datalab/lib/pydatalab/.git ]; then         echo "use local lib";       else         git clone https://github.com/googledatalab/pydatalab.git /datalab/lib/pydatalab;       fi &&     cd /datalab/lib/pydatalab &&     /tools/node/bin/npm install -g typescript &&     tsc --module amd --noImplicitAny --outdir datalab/notebook/static datalab/notebook/static/*.ts &&     /tools/node/bin/npm uninstall -g typescript &&     pip install --upgrade-strategy only-if-needed --no-cache-dir . &&     jupyter nbextension install --py datalab.notebook &&     jupyter nbextension enable --py widgetsnbextension &&     rm datalab/notebook/static/*.js &&     mkdir -p /datalab/nbconvert &&     cp -R /usr/local/share/jupyter/nbextensions/gcpdatalab/* /datalab/nbconvert &&     ln -s /usr/local/lib/python2.7/dist-packages/notebook/static/custom/custom.css /datalab/nbconvert/custom.css &&     mkdir -p /usr/local/lib/python2.7/dist-packages/notebook/static/components/codemirror/mode/text/sql/text &&     ln -s /usr/local/share/jupyter/nbextensions/gcpdatalab/codemirror/mode/sql.js /usr/local/lib/python2.7/dist-packages/notebook/static/components/codemirror/mode/text/sql/text/sql.js &&     cd /' returned a non-zero code: 2
```
