### ISSUE TITLE
"No JSON object could be decoded" error on connecting to a Datalab GCE instance

### ISSUE THREAD

**Issue by kazunori279** [googledatalab/datalab#1197]
I've done:

- Created Datalab instance with "datalab create" command (after "gcloud components update")
- At the last of the create command, I was able to connect the instance with my local browser
- But "datalab connect" command returns the following error every time:

Traceback (most recent call last):
  File "/Users/kazsato/google-cloud-sdk/platform/datalab-cli/datalab.py", line 234, in <module>
    run()
  File "/Users/kazsato/google-cloud-sdk/platform/datalab-cli/datalab.py", line 228, in run
    in_cloud_shell=('DEVSHELL_CLIENT_PORT' in os.environ))
  File "/Users/kazsato/google-cloud-sdk/platform/datalab-cli/commands/connect.py", line 355, in run
    args, gcloud_compute, instance)
  File "/Users/kazsato/google-cloud-sdk/platform/datalab-cli/commands/utils.py", line 120, in describe_instance
    args, gcloud_compute, instance)
  File "/Users/kazsato/google-cloud-sdk/platform/datalab-cli/commands/utils.py", line 109, in describe_instance
    status_and_metadata = json.loads(json_result)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by ojarjur** [comment]
Thanks for reporting this.

Looking at the relevant code, I think there is a bug where we include the stderr from `gcloud` when trying to parse the result of the `gcloud compute instances describe` command.

That's not correct, since only the stdout will have the JSON result we want to parse.

I'll get that fixed, but in the meantime you can try to see what is being written to stderr by running:

    gcloud compute instances describe --project <YOUR-PROJECT> --zone <YOUR-ZONE> --format "json(status,metadata.items)" <YOUR-INSTANCE>

... and see what it spits out in addition to the JSON output. If that is something that can be silenced, then that might unblock you.
