### ISSUE TITLE
Query Execute to DataFrame raise exception for ZERO length result

### ISSUE THREAD

**Issue by HaipengSu** [googledatalab/datalab#1332]
`import google.datalab.bigquery as bq`

```
%%bq query -n testQuery

Select * 
From `bigquery-public-data.hacker_news.comments`
Limit 0
```

`testQuery.execute(output_options=bq.QueryOutput.dataframe()).result()`

As Shown above, I tried different queries, as long as the query result has ZERO row, the execution will return an exception.  Is this a bug?  Thank you.

```
JobErrorTraceback (most recent call last)
<ipython-input-3-9a97435cea10> in <module>()
----> 1 testQuery.execute(output_options=bq.QueryOutput.dataframe()).result()

/usr/local/lib/python2.7/dist-packages/google/datalab/_job.pyc in result(self)
    129     self.wait()
    130     if self._fatal_error:
--> 131       raise self._fatal_error
    132     return self._result
    133 

JobError: No objects to concatenate <type 'exceptions.ValueError'> Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/google/datalab/_job.py", line 165, in _refresh_state
    self._result = self._future.result()
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/google/datalab/utils/_async.py", line 66, in _call
    return self._function(*async._preprocess_args(*args), **async._preprocess_kwargs(**kwargs))
  File "/usr/local/lib/python2.7/dist-packages/google/datalab/bigquery/_table.py", line 620, in to_dataframe
    df = pandas.concat(df_list, ignore_index=True, copy=False)
  File "/usr/local/lib/python2.7/dist-packages/pandas/tools/merge.py", line 1334, in concat
    copy=copy)
  File "/usr/local/lib/python2.7/dist-packages/pandas/tools/merge.py", line 1367, in __init__
    raise ValueError('No objects to concatenate')
ValueError: No objects to concatenate
```

**Comment by HaipengSu** [comment]
I  am trying to build Datalab from source and fix the issue, hope this would help. Thx

**Comment by yebrahim** [comment]
Looks like a legitimate bug. A fix would be welcome.

**Comment by yebrahim** [comment]
Closed by https://github.com/googledatalab/pydatalab/pull/362.
