### ISSUE TITLE
Update Node Version in Development Environment wiki page

### ISSUE THREAD

**Issue by parthea** [googledatalab/datalab#1441]
The [Development Environment wiki page](https://github.com/googledatalab/datalab/wiki/Development-Environment) indicates that NodeJS 0.12.x is required but when I try to build from source I found that Node version 6 is needed. With version 0.12.x, I received the following error:
```
tony@tony-laptop:~/Git/parthea-datalab/sources$ ./build.sh 
git version 2.9.3
Installing Polymer CLI
▌ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine polymer-cli@1.2.0: wanted: {"node":">=6.0"} (current: {"node":"4.2.6","npm":"3.5.2"})
WARN engine polymer-cli@1.2.0: wanted: {"node":">=6.0"} (current: {"node":"4.2.6loadDep:yeoman-generator  ▐ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine polymer-analyzer@2.1.0: wanted: {"node":">=6"} (current: {"node":"4.loadDep:yeoman-generator  ▀ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine polymer-linter@2.0.2: wanted: {"node":">=6"} (current: {"node":"4.2.6","npm":"3.5.2"})
WARN engine web-component-tester@6.0.0: wanted: {"node":">= 6.0"} (current: {"nonpm WARN deprecated bower@1.8.0: ..psst! While Bower is maintained, we recommend Yarn and Webpack for *new* front-end projects! Yarn's advantage is security and reliability, and Webpack's is support for both CommonJS and AMD projects. Currently there's no migration path but we hope you'll help us figure out one.
npm WARN deprecated @types/assert@0.0.29: See https://github.com/DefinitelyTyped/DefinitelyTyped/issues/12826
loadDep:selenium-standalo ▌ ╢██████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine launchpad@0.6.0: wanted: {"node":"^0.12"} (current: {"node":"4.2.6",/usr/local/bin/polymer -> /usr/local/lib/node_modules/polymer-cli/bin/polymer.js

> sauce-connect-launcher@1.2.2 postinstall /usr/local/lib/node_modules/polymer-cli/node_modules/sauce-connect-launcher
> node scripts/install.js || nodejs scripts/install.js


> wct-sauce@2.0.0-pre.1 postinstall /usr/local/lib/node_modules/polymer-cli/node_modules/wct-sauce
> node scripts/postinstall.js

/usr/local/lib/node_modules/polymer-cli/node_modules/sauce-connect-launcher/lib/sauce-connect-launcher.js:128
        fs.chmod(bin, 0o755, function (err) {
                      ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/wct-sauce/lib/sauce.js:15:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

```

I installed NodeJS version 6.10.0 and the above issue was resolved.
https://github.com/googledatalab/datalab/blob/aa41a586ecd98b9ed4e4b5b99905e8c0a6255afe/sources/build.sh#L28 

Note that this issue may be merged into #1334 .

**Comment by brandondutra** [comment]
I hit this error too. I'll update the page
