### ISSUE TITLE
connection issue with datalab

### ISSUE THREAD

**Issue by eilalan** [googledatalab/datalab#1939]
Hello, 

I am using datalab connect to an already exist (and in use) datalab vm. everything looks fine on the cloud shell, however, the connection on the browser is not presenting anything and reaches time out. following is the logs from $sudo journalctl -u datalab
```
-- Reboot --
Feb 05 15:39:02 d3 systemd[1]: Starting datalab docker container...
Feb 05 15:39:02 d3 docker-credential-gcr[1059]: /home/datalab/.docker/config.json configured to use this credential helper for GCR registries
Feb 05 15:39:02 d3 systemd[1]: Started datalab docker container.
Feb 05 15:39:05 d3 docker[1075]: Using mount point: /content/datalab/bucket-share
Feb 05 15:39:05 d3 docker[1075]: Opening GCS connection...
Feb 05 15:39:05 d3 docker[1075]: Opening bucket...
Feb 05 15:39:07 d3 docker[1075]: Mounting file system...
Feb 05 15:39:07 d3 docker[1075]: File system has been successfully mounted.
Feb 05 15:39:16 d3 docker[1075]: Verifying that the /tmp directory is writable
Feb 05 15:39:16 d3 docker[1075]: The /tmp directory is writable
Feb 05 15:39:16 d3 docker[1075]: / /
Feb 05 15:39:18 d3 docker[1075]: From https://github.com/googledatalab/notebooks
Feb 05 15:39:18 d3 docker[1075]:  * branch            master     -> FETCH_HEAD
Feb 05 15:39:18 d3 docker[1075]:    3bfa9ce..8ef5ceb  master     -> origin/master
Feb 05 15:39:18 d3 docker[1075]: HEAD is now at 8ef5ceb Add instructions for viewing Airflow Dashboard with ssh tunnel (#149)
Feb 05 15:39:18 d3 docker[1075]: /
Feb 05 15:39:18 d3 docker[1075]: Already on 'master'
Feb 05 15:39:18 d3 docker[1075]: Your branch is up-to-date with 'origin/master'.
Feb 05 15:39:19 d3 docker[1075]: Open your browser to http://localhost:8081/ to connect to Datalab.
Feb 05 16:25:11 d3 docker[1075]: {"name":"app","hostname":"31447e62133b","pid":113,"level":50,"err":{"message":"timeout","name":"Error","stack":"Error: timeout\n    at Timeout.timeoutFunc (/datalab/web/node_modules/tcp-port-used/index.js:192:25)\n    at ontimeout (timers.js:365:14)\n    at tryOnTimeout (timers.js:237:5)\n    at Timer.listOnTimeout (timers.js:207:5)"},"msg":"Failed to start Jupyter server for user anonymous.","time":"2018-02-05T16:24:51.739Z","v":0}
Feb 05 16:25:13 d3 docker[1075]: {"name":"app","hostname":"31447e62133b","pid":113,"level":50,"err":{"message":"timeout","name":"Error","stack":"Error: timeout\n    at Timeout.timeoutFunc (/datalab/web/node_modules/tcp-port-used/index.js:192:25)\n    at ontimeout (timers.js:365:14)\n    at tryOnTimeout (timers.js:237:5)\n    at Timer.listOnTimeout (timers.js:207:5)"},"msg":"Failed to start Jupyter server for user anonymous.","time":"2018-02-05T16:25:08.963Z","v":0}
Feb 05 16:25:36 d3 docker[1075]: {"name":"app","hostname":"31447e62133b","pid":113,"level":50,"err":{"message":"timeout","name":"Error","stack":"Error: timeout\n    at Timeout.timeoutFunc (/datalab/web/node_modules/tcp-port-used/index.js:192:25)\n    at ontimeout (timers.js:365:14)\n    at tryOnTimeout (timers.js:237:5)\n    at Timer.listOnTimeout (timers.js:207:5)"},"msg":"Failed to start Jupyter server for user anonymous.","time":"2018-02-05T16:25:36.753Z","v":0}
Feb 05 16:26:55 d3 docker[1075]: {"name":"app","hostname":"31447e62133b","pid":113,"level":50,"msg":"Jupyter process 3486 for user anonymous exited due to signal: null","time":"2018-02-05T16:26:52.718Z","v":0}
Feb 05 16:26:55 d3 docker[1075]: {"name":"app","hostname":"31447e62133b","pid":113,"level":50,"msg":"Jupyter process 3488 for user anonymous exited due to signal: null","time":"2018-02-05T16:26:52.722Z","v":0}
Feb 05 16:27:02 d3 docker[1075]: {"name":"app","hostname":"31447e62133b","pid":113,"level":50,"err":{"message":"timeout","name":"Error","stack":"Error: timeout\n    at Timeout.timeoutFunc (/datalab/web/node_modules/tcp-port-used/index.js:192:25)\n    at ontimeout (timers.js:365:14)\n    at tryOnTimeout (timers.js:237:5)\n    at Timer.listOnTimeout (timers.js:207:5)"},"msg":"Failed to start Jupyter server for user anonymous.","time":"2018-02-05T16:27:01.722Z","v":0}
Feb 05 16:27:22 d3 docker[1075]: {"name":"app","hostname":"31447e62133b","pid":113,"level":50,"err":{"message":"timeout","name":"Error","stack":"Error: timeout\n    at Timeout.timeoutFunc (/datalab/web/node_modules/tcp-port-used/index.js:192:25)\n    at ontimeout (timers.js:365:14)\n    at tryOnTimeout (timers.js:237:5)\n    at Timer.listOnTimeout (timers.js:207:5)"},"msg":"Failed to start Jupyter server for user anonymous.","time":"2018-02-05T16:27:22.736Z","v":0}
Feb 05 16:27:49 d3 docker[1075]: {"name":"app","hostname":"31447e62133b","pid":113,"level":50,"err":{"message":"timeout","name":"Error","stack":"Error: timeout\n    at Timeout.timeoutFunc (/datalab/web/node_modules/tcp-port-used/index.js:192:25)\n    at ontimeout (timers.js:365:14)\n    at tryOnTimeout (timers.js:237:5)\n    at Timer.listOnTimeout (timers.js:207:5)"},"msg":"Failed to start Jupyter server for user anonymous.","time":"2018-02-05T16:27:49.757Z","v":0}
Feb 05 16:28:19 d3 docker[1075]: {"name":"app","hostname":"31447e62133b","pid":113,"level":50,"err":{"message":"timeout","name":"Error","stack":"Error: timeout\n    at Timeout.timeoutFunc (/datalab/web/node_modules/tcp-port-used/index.js:192:25)\n    at ontimeout (timers.js:365:14)\n    at tryOnTimeout (timers.js:237:5)\n    at Timer.listOnTimeout (timers.js:207:5)"},"msg":"Failed to start Jupyter server for user anonymous.","time":"2018-02-05T16:28:18.968Z","v":0}
Feb 05 16:29:10 d3 docker[1075]: {"name":"app","hostname":"31447e62133b","pid":113,"level":50,"msg":"Jupyter process 3508 for user anonymous exited due to signal: null","time":"2018-02-05T16:29:09.486Z","v":0}
Feb 05 16:29:10 d3 docker[1075]: {"name":"app","hostname":"31447e62133b","pid":113,"level":50,"msg":"Jupyter process 3507 for user anonymous exited due to signal: null","time":"2018-02-05T16:29:09.766Z","v":0}
Feb 05 16:30:46 d3 docker[1075]: {"name":"app","hostname":"31447e62133b","pid":113,"level":50,"msg":"Jupyter process 3522 for user anonymous exited due to signal: null","time":"2018-02-05T16:30:43.760Z","v":0}
Feb 05 16:31:22 d3 docker[1075]: {"name":"app","hostname":"31447e62133b","pid":113,"level":50,"msg":"Jupyter process 3529 for user anonymous exited due to signal: null","time":"2018-02-05T16:31:20.468Z","v":0}
Feb 05 16:41:35 d3 docker[1075]: {"name":"app","hostname":"31447e62133b","pid":113,"level":50,"err":{"message":"timeout","name":"Error","stack":"Error: timeout\n    at Timeout.timeoutFunc (/datalab/web/node_modules/tcp-port-used/index.js:192:25)\n    at ontimeout (timers.js:365:14)\n    at tryOnTimeout (timers.js:237:5)\n    at Timer.listOnTimeout (timers.js:207:5)"},"msg":"Failed to start Jupyter server for user anonymous.","time":"2018-02-05T16:41:31.761Z","v":0}
Feb 05 16:47:13 d3 docker[1075]: {"name":"app","hostname":"31447e62133b","pid":113,"level":50,"msg":"Jupyter process 4851 for user anonymous exited due to signal: null","time":"2018-02-05T16:47:11.602Z","v":0}
Feb 05 16:47:27 d3 docker[1075]: {"name":"app","hostname":"31447e62133b","pid":113,"level":50,"err":{"message":"timeout","name":"Error","stack":"Error: timeout\n    at Timeout.timeoutFunc (/datalab/web/node_modules/tcp-port-used/index.js:192:25)\n    at ontimeout (timers.js:365:14)\n    at tryOnTimeout (timers.js:237:5)\n    at Timer.listOnTimeout (timers.js:207:5)"},"msg":"Failed to start Jupyter server for user anonymous.","time":"2018-02-05T16:47:27.011Z","v":0}
Feb 05 16:48:17 d3 docker[1075]: {"name":"app","hostname":"31447e62133b","pid":113,"level":50,"err":{"message":"timeout","name":"Error","stack":"Error: timeout\n    at Timeout.timeoutFunc (/datalab/web/node_modules/tcp-port-used/index.js:192:25)\n    at ontimeout (timers.js:365:14)\n    at tryOnTimeout (timers.js:237:5)\n    at Timer.listOnTimeout (timers.js:207:5)"},"msg":"Failed to start Jupyter server for user anonymous.","time":"2018-02-05T16:48:15.743Z","v":0}
Feb 05 16:49:40 d3 docker[1075]: {"name":"app","hostname":"31447e62133b","pid":113,"level":50,"err":{"message":"timeout","name":"Error","stack":"Error: timeout\n    at Timeout.timeoutFunc (/datalab/web/node_modules/tcp-port-used/index.js:192:25)\n    at ontimeout (timers.js:365:14)\n    at tryOnTimeout (timers.js:237:5)\n    at Timer.listOnTimeout (timers.js:207:5)"},"msg":"Failed to start Jupyter server for user anonymous.","time":"2018-02-05T16:49:38.516Z","v":0}
Feb 05 16:50:00 d3 docker[1075]: {"name":"app","hostname":"31447e62133b","pid":113,"level":50,"msg":"Jupyter process 5260 for user anonymous exited due to signal: null","time":"2018-02-05T16:49:59.999Z","v":0}
Feb 05 16:52:48 d3 docker[1075]: {"name":"app","hostname":"31447e62133b","pid":113,"level":50,"msg":"Jupyter process 5274 for user anonymous exited due to signal: null","time":"2018-02-05T16:52:39.246Z","v":0}
```

any idea what might be the issue
Thanks,
Eila

**Comment by eilalan** [comment]
I have fixed that issue. Increasing the resources made the trick
