### ISSUE TITLE
SSH error on `datalab connect`

### ISSUE THREAD

**Issue by gitrago** [googledatalab/datalab#1973]
I can successfully log on to a compute instance  with the command ` gcloud compute --project "elkinter" ssh --zone "europe-west1-c" "elkinter-datalab" ` but I can not connect with 

```
datalab connect elkinter-datalab --no-user-checking --verbosity debug --ssh-log-level debug1 --port 8085

Connecting to belkinter-datalab.
This will create an SSH tunnel and may prompt you to create an rsa key pair. To manage these keys, see https://cloud.google.com/compute/docs/instances/adding-removing-ssh-keys
Waiting for Datalab to be reachable at http://localhost:8085/Connecting to elkinter-datalab via SSH

DEBUG: Running [gcloud.compute.ssh] with arguments: [--ssh-flag: "['-o', 'LogLevel=debug1', '-4', '-N', '-L', 'localhost:8085:localhost:8080']", --verbosity: "debug", --zone: "europe-west1-c", [USER@]INSTANCE: "datalab@elkinter-datalab"]
DEBUG: Current SSH keys in project: [u'datalab:ssh-rsa AAAAB3NzaC1yc2EAAAADA<<removed for brevity>>qE2HALtuxhVf16vLBIxBxGBexBnzWy4dCEQQ65HwUxKGbJamypP9mF39rddGv4ft2Ns4ePYVYB8Nzvj user@thing']
DEBUG: Running command [/usr/bin/ssh -t -i /Users/user/.ssh/google_compute_engine -o CheckHostIP=no -o HostKeyAlias=compute.7273819897325272753 -o IdentitiesOnly=yes -o StrictHostKeyChecking=yes -o UserKnownHostsFile=/Users/user/.ssh/google_compute_known_hosts -o LogLevel=debug1 -4 -N -L localhost:8085:localhost:8080 datalab@35.205.47.157].
DEBUG: Executing command: [u'/usr/bin/ssh', '-t', '-i', '/Users/user/.ssh/google_compute_engine', '-o', 'CheckHostIP=no', '-o', 'HostKeyAlias=compute.7273819897325272753', '-o', 'IdentitiesOnly=yes', '-o', 'StrictHostKeyChecking=yes', '-o', 'UserKnownHostsFile=/Users/user/.ssh/google_compute_known_hosts', u'-o', u'LogLevel=debug1', u'-4', u'-N', u'-L', u'localhost:8085:localhost:8080', u'datalab@35.205.47.157']
debug1: Reading configuration data /Users/user/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 48: Applying options for *
debug1: Connecting to 35.205.47.157 port 22.
debug1: Connection established.
debug1: identity file /Users/user/.ssh/google_compute_engine type 0
debug1: key_load_public: No such file or directory
debug1: identity file /Users/user/.ssh/google_compute_engine-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_7.6
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.5
debug1: match: OpenSSH_7.5 pat OpenSSH* compat 0x04000000
debug1: Authenticating to 35.205.47.157:22 as 'datalab'
debug1: using hostkeyalias: compute.7273819897325272753
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: rsa-sha2-512
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ssh-rsa SHA256:TBOgiAHfiHZVDypBRsSwIeEloCtw+pnSJtdhJJ/UZLM
debug1: using hostkeyalias: compute.7273819897325272753
debug1: Host 'compute.7273819897325272753' is known and matches the RSA host key.
debug1: Found key in /Users/user/.ssh/google_compute_known_hosts:1
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering public key: RSA SHA256:ZLBJkV9VPNJpZ9vmLK/Y8RJQE1lbPDB8X2Kime0iTuI /Users/user/.ssh/google_compute_engine
debug1: Authentications that can continue: publickey
debug1: No more authentication methods to try.
datalab@35.205.47.157: Permission denied (publickey).
DEBUG: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].
Traceback (most recent call last):
  File "/Users/xp/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 797, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/Users/xp/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 757, in Run
    resources = command_instance.Run(args)
  File "/Users/xp/google-cloud-sdk/lib/surface/compute/ssh.py", line 195, in Run
    return_code = cmd.Run(ssh_helper.env, force_connect=True)
  File "/Users/xp/google-cloud-sdk/lib/googlecloudsdk/command_lib/util/ssh/ssh.py", line 934, in Run
    raise CommandError(args[0], return_code=status)
CommandError: [/usr/bin/ssh] exited with return code [255].
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].
Connection broken
Attempting to reconnect...
```

Once I logged in with `cloud compute ssh`, I see the two docker images with `dossier ps` and if I issue `curl localhost:8080/_info` I get this:

```
<...many lines...>
Request Headers:
accept: */*
host: localhost:8080
user-agent: curl/7.56.1

Jupyter Servers:
[
  {
    "userId": "anonymous",
    "port": 9000,
    "notebooks": "/content",
    "pid": 199
  }
]

```

I tried different `--port` values. I see this **"port: 9000"** for Jupyter and wonder if that is legit... I added an "**enable-oslogin**" metadata entry and set it to False for good measure. Ran out of things to try. Please help.

**Comment by chmeyers** [comment]
This sounds like https://github.com/googledatalab/datalab/issues/1932, assuming this is a new datalab instance.

Try using the latest version of the datalab command ('gcloud components update') and re-creating the datalab instance.

**Comment by ojarjur** [comment]
@chmeyers I don't think this is related to #1932; that one was the SSH key being protected by a passphrase. If that was the case here, then the `gcloud compute ssh ...` command would be hitting the same issue.

However, this could be #1936 

@gitrago You can check this by running `gcloud compute --project "${PROJECT_ID}" ssh --zone "${ZONE}" datalab@${INSTANCE}` (after setting all of those envrionment variables), and see if that works. If that fails, then it is probably #1936, and the suggestion from Chris to upgrade gcloud and recreate the instance is your best bet.

**Comment by gitrago** [comment]
gcloud is up to date, I updated it first thing just forgot to mention.  `/home/datalab` folder is not owned by root but it is not owned by user `datalab` either: it is owned by the user who originally created the instance. I was attempting to connect with the flag `--no-user-checking`

**Comment by ojarjur** [comment]
@gitrago If `/home/datalab` is not owned by the user `datalab`, then you won't be able to connect to the instance.

You can fix that by using gcloud to SSH in and then running `sudo chown -R datalab /home/datalab`

I do not know of any scenario that would cause the `/home/datalab` folder to be owned by an account associated with the user who created the instance, so I do not know how this instance could have gotten into that state, but running the `chown` command above *should* fix it.

**Comment by ojarjur** [comment]
Since it's been a while since this was last updated, I will assume that fixing the folder permissions fixed the issue and close this out.

@gitrago If things aren't working or this same situation happens again, then please let us know.
